export const wideButton: string;
export const main: string;
export const titleSection: string;
export const instructions: string;
export const error: string;
export const customInput: string;
export const customInputError: string;
export const inputFields: string;
export const actionsContainer: string;
