export const inboxContainerFull: string;
export const inboxContainerPopover: string;
export const contentContainerFull: string;
export const contentContainerPopup: string;
export const inboxHeadingFull: string;
export const inboxHeadingPopover: string;
export const inboxFooter: string;
export const loadingText: string;
export const emptyText: string;
