/* @flow */

export const SET_CURRENT_USER = 'users/SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'users/SET_CURRENT_USER_ERROR';
export const SET_CURRENT_USER_SUCCESS = 'users/SET_CURRENT_USER_SUCCESS';

export const USER_PROFILE_UPDATE = 'users/USER_PROFILE_UPDATE';
export const USER_PROFILE_UPDATE_ERROR = 'users/USER_PROFILE_UPDATE_ERROR';
export const USER_PROFILE_UPDATE_SUCCESS = 'users/USER_PROFILE_UPDATE_SUCCESS';
