/* @flow */

export const SET_CURRENT_USER = 'users/SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'users/SET_CURRENT_USER_ERROR';

export const UPDATE_USER_PROFILE = 'users/UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_ERROR = 'users/UPDATE_USER_PROFILE_ERROR';
export const UPDATE_USER_PROFILE_SUCCESS = 'users/UPDATE_USER_PROFILE_SUCCESS';
