/* @flow */

import { USERS_NAMESPACE as ns } from '../constants';

/*
 * User Action Types
 */

export const USER_ACTIVITIES_FETCH = `${ns}/USER_ACTIVITIES_FETCH`;
export const USER_ACTIVITIES_FETCH_ERROR = `${ns}/USER_ACTIVITIES_FETCH_ERROR`;
export const USER_ACTIVITIES_FETCH_SUCCESS = `${ns}/USER_ACTIVITIES_FETCH_SUCCESS`;

export const USER_PROFILE_FETCH = `${ns}/USER_PROFILE_FETCH`;
export const USER_PROFILE_FETCH_ERROR = `${ns}/USER_PROFILE_FETCH_ERROR`;
export const USER_PROFILE_FETCH_SUCCESS = `${ns}/USER_PROFILE_FETCH_SUCCESS`;

export const USER_AVATAR_FETCH = `${ns}/USER_AVATAR_FETCH`;
export const USER_AVATAR_FETCH_ERROR = `${ns}/USER_AVATAR_FETCH_ERROR`;
export const USER_AVATAR_FETCH_SUCCESS = `${ns}/USER_AVATAR_FETCH_SUCCESS`;

export const USERNAME_FETCH = `${ns}/USERNAME_FETCH`;
export const USERNAME_FETCH_ERROR = `${ns}/USERNAME_FETCH_ERROR`;
export const USERNAME_FETCH_SUCCESS = `${ns}/USERNAME_FETCH_SUCCESS`;
