export const container: string;
export const dot: string;
export const verticalLine: string;
export const activeDot: string;
export const verticalLineActive: string;
export const label: string;
export const activeLabel: string;
export const cancelled: string;
export const cancelledLabel: string;
