export const formContainer: string;
export const activeItemLabel: string;
export const lockedActiveItemLabel: string;
export const valueAmount: string;
export const tokenIcon: string;
export const symbol: string;
export const icon: string;
export const activeItem: string;
export const row: string;
