export const main: string;
export const delegate: string;
export const checkbox: string;
export const stateIsChecked: string;
export const checkmark: string;
export const themeDark: string;
export const directionHorizontal: string;
export const directionVertical: string;
export const stateDisabled: string;
