export const cellPadding: string;
export const nameMargin: string;
export const main: string;
export const customRemoveButton: string;
export const customEditButton: string;
export const domainDetails: string;
export const domainRemove: string;
export const domainName: string;
export const contributions: string;
