/* @flow */

import { DASHBOARD_NAMESPACE as ns } from '../constants';

export const COLONY_ADMIN_ADD = `${ns}/COLONY_ADMIN_ADD`;
export const COLONY_ADMIN_ADD_SUCCESS = `${ns}/COLONY_ADMIN_ADD_SUCCESS`;
export const COLONY_ADMIN_ADD_ERROR = `${ns}/COLONY_ADMIN_ADD_ERROR`;

export const COLONY_ADMIN_ADD_CONFIRM = `${ns}/COLONY_ADMIN_ADD_CONFIRM`;
export const COLONY_ADMIN_ADD_CONFIRM_SUCCESS = `${ns}/COLONY_ADMIN_ADD_CONFIRM_SUCCESS`;
export const COLONY_ADMIN_ADD_CONFIRM_ERROR = `${ns}/COLONY_ADMIN_ADD_CONFIRM_ERROR`;

export const COLONY_ADMIN_REMOVE = `${ns}/COLONY_ADMIN_REMOVE`;
export const COLONY_ADMIN_REMOVE_SUCCESS = `${ns}/COLONY_ADMIN_REMOVE_SUCCESS`;
export const COLONY_ADMIN_REMOVE_ERROR = `${ns}/COLONY_ADMIN_REMOVE_ERROR`;

export const COLONY_ADMIN_REMOVE_CONFIRM = `${ns}/COLONY_ADMIN_REMOVE_CONFIRM`;
export const COLONY_ADMIN_REMOVE_CONFIRM_SUCCESS = `${ns}/COLONY_ADMIN_REMOVE_CONFIRM_SUCCESS`;
export const COLONY_ADMIN_REMOVE_CONFIRM_ERROR = `${ns}/COLONY_ADMIN_REMOVE_CONFIRM_ERROR`;
