/* @flow */

import ns from '../namespace';

export const TOKEN_CREATE = `${ns}/TOKEN_CREATE`;
export const TOKEN_CREATE_ERROR = `${ns}/TOKEN_CREATE_ERROR`;
export const TOKEN_CREATE_SUCCESS = `${ns}/TOKEN_CREATE_SUCCESS`;

export const COLONY_CREATE = `${ns}/COLONY_CREATE`;
export const COLONY_CREATE_ERROR = `${ns}/COLONY_CREATE_ERROR`;
export const COLONY_CREATE_SUCCESS = `${ns}/COLONY_CREATE_SUCCESS`;

export const TOKEN_INFO_FETCH = `${ns}/TOKEN_INFO_FETCH`;
export const TOKEN_INFO_FETCH_ERROR = `${ns}/TOKEN_INFO_FETCH_ERROR`;
export const TOKEN_INFO_FETCH_SUCCESS = `${ns}/TOKEN_INFO_FETCH_SUCCESS`;

export const COLONY_CREATE_LABEL = `${ns}/COLONY_CREATE_LABEL`;
export const COLONY_CREATE_LABEL_ERROR = `${ns}/COLONY_CREATE_LABEL_ERROR`;
export const COLONY_CREATE_LABEL_SUCCESS = `${ns}/COLONY_CREATE_LABEL_SUCCESS`;
