/* @flow */
/* eslint-disable max-len */

import ns from '../namespace';

export const COLONY_FETCH = `${ns}/COLONY_FETCH`;
export const COLONY_FETCH_SUCCESS = `${ns}/COLONY_FETCH_SUCCESS`;
export const COLONY_FETCH_ERROR = `${ns}/COLONY_FETCH_ERROR`;

export const COLONY_CREATE = `${ns}/COLONY_CREATE`;
export const COLONY_CREATE_ERROR = `${ns}/COLONY_CREATE_ERROR`;
export const COLONY_CREATE_SUCCESS = `${ns}/COLONY_CREATE_SUCCESS`;

export const COLONY_CREATE_LABEL = `${ns}/COLONY_CREATE_LABEL`;
export const COLONY_CREATE_LABEL_ERROR = `${ns}/COLONY_CREATE_LABEL_ERROR`;
export const COLONY_CREATE_LABEL_SUCCESS = `${ns}/COLONY_CREATE_LABEL_SUCCESS`;

export const COLONY_PROFILE_UPDATE = `${ns}/COLONY_PROFILE_UPDATE`;
export const COLONY_PROFILE_UPDATE_ERROR = `${ns}/COLONY_PROFILE_UPDATE_ERROR`;
export const COLONY_PROFILE_UPDATE_SUCCESS = `${ns}/COLONY_PROFILE_UPDATE_SUCCESS`;
