/* @flow */

import { DASHBOARD_NAMESPACE as ns } from '../constants';

export const COLONY_FETCH = `${ns}/COLONY_FETCH`;
export const COLONY_FETCH_SUCCESS = `${ns}/COLONY_FETCH_SUCCESS`;
export const COLONY_FETCH_ERROR = `${ns}/COLONY_FETCH_ERROR`;

export const COLONY_CREATE = `${ns}/COLONY_CREATE`;
export const COLONY_CREATE_SUCCESS = `${ns}/COLONY_CREATE_SUCCESS`;
export const COLONY_CREATE_ERROR = `${ns}/COLONY_CREATE_ERROR`;

export const COLONY_CREATE_LABEL = `${ns}/COLONY_CREATE_LABEL`;
export const COLONY_CREATE_LABEL_SUCCESS = `${ns}/COLONY_CREATE_LABEL_SUCCESS`;
export const COLONY_CREATE_LABEL_ERROR = `${ns}/COLONY_CREATE_LABEL_ERROR`;

export const COLONY_PROFILE_UPDATE = `${ns}/COLONY_PROFILE_UPDATE`;
export const COLONY_PROFILE_UPDATE_SUCCESS = `${ns}/COLONY_PROFILE_UPDATE_SUCCESS`;
export const COLONY_PROFILE_UPDATE_ERROR = `${ns}/COLONY_PROFILE_UPDATE_ERROR`;

export const COLONY_AVATAR_UPLOAD = `${ns}/COLONY_AVATAR_UPLOAD`;
export const COLONY_AVATAR_UPLOAD_SUCCESS = `${ns}/COLONY_AVATAR_UPLOAD_SUCCESS`;
export const COLONY_AVATAR_UPLOAD_ERROR = `${ns}/COLONY_AVATAR_UPLOAD_ERROR`;

export const COLONY_AVATAR_REMOVE = `${ns}/COLONY_AVATAR_REMOVE`;
export const COLONY_AVATAR_REMOVE_SUCCESS = `${ns}/COLONY_AVATAR_REMOVE_SUCCESS`;
export const COLONY_AVATAR_REMOVE_ERROR = `${ns}/COLONY_AVATAR_REMOVE_ERROR`;

export const COLONY_AVATAR_FETCH = `${ns}/COLONY_AVATAR_FETCH`;
export const COLONY_AVATAR_FETCH_SUCCESS = `${ns}/COLONY_AVATAR_FETCH_SUCCESS`;
export const COLONY_AVATAR_FETCH_ERROR = `${ns}/COLONY_AVATAR_FETCH_ERROR`;

export const COLONY_DOMAIN_ADD = `${ns}/COLONY_DOMAIN_ADD`;
export const COLONY_DOMAIN_ADD_SUCCESS = `${ns}/COLONY_DOMAIN_ADD_SUCCESS`;
export const COLONY_DOMAIN_ADD_ERROR = `${ns}/COLONY_DOMAIN_ADD_ERROR`;

export const COLONY_DOMAIN_REMOVE = `${ns}/COLONY_DOMAIN_REMOVE`;
export const COLONY_DOMAIN_REMOVE_SUCCESS = `${ns}/COLONY_DOMAIN_REMOVE_SUCCESS`;
export const COLONY_DOMAIN_REMOVE_ERROR = `${ns}/COLONY_DOMAIN_REMOVE_ERROR`;

export const COLONY_ENS_NAME_FETCH = `${ns}/COLONY_ENS_NAME_FETCH`;
export const COLONY_ENS_NAME_FETCH_ERROR = `${ns}/COLONY_ENS_NAME_FETCH_ERROR`;
export const COLONY_ENS_NAME_FETCH_SUCCESS = `${ns}/COLONY_ENS_NAME_FETCH_SUCCESS`;
