/* @flow */

import ns from '../namespace';

export const COLONY_DOMAIN_VALIDATE = `${ns}/COLONY_DOMAIN_VALIDATE`;
export const COLONY_DOMAIN_VALIDATE_SUCCESS = `${ns}/COLONY_DOMAIN_VALIDATE_SUCCESS`;
export const COLONY_DOMAIN_VALIDATE_ERROR = `${ns}/COLONY_DOMAIN_VALIDATE_ERROR`;

export const DOMAIN_CREATE = `${ns}/DOMAIN_CREATE`;
export const DOMAIN_CREATE_ERROR = `${ns}/DOMAIN_CREATE_ERROR`;
export const DOMAIN_CREATE_SUCCESS = `${ns}/DOMAIN_CREATE_SUCCESS`;

export const DOMAIN_CREATE_LABEL = `${ns}/DOMAIN_CREATE_LABEL`;
export const DOMAIN_CREATE_LABEL_ERROR = `${ns}/DOMAIN_CREATE_LABEL_ERROR`;
export const DOMAIN_CREATE_LABEL_SUCCESS = `${ns}/DOMAIN_CREATE_LABEL_SUCCESS`;

export const DOMAIN_FETCH = `${ns}/DOMAIN_FETCH`;
export const DOMAIN_FETCH_ERROR = `${ns}/DOMAIN_FETCH_ERROR`;
export const DOMAIN_FETCH_SUCCESS = `${ns}/DOMAIN_FETCH_SUCCESS`;

export const ROOT_DOMAIN_FETCH = `${ns}/DOMAIN_FETCH`;
export const ROOT_DOMAIN_FETCH_ERROR = `${ns}/DOMAIN_FETCH_ERROR`;
export const ROOT_DOMAIN_FETCH_SUCCESS = `${ns}/DOMAIN_FETCH_SUCCESS`;

export const TASKDRAFT_FETCH = `${ns}/TASKDRAFT_FETCH`;
