/* @flow */

import { DASHBOARD_NAMESPACE as ns } from '../constants';

export const COLONY_DOMAIN_VALIDATE = `${ns}/COLONY_DOMAIN_VALIDATE`;
export const COLONY_DOMAIN_VALIDATE_SUCCESS = `${ns}/COLONY_DOMAIN_VALIDATE_SUCCESS`;
export const COLONY_DOMAIN_VALIDATE_ERROR = `${ns}/COLONY_DOMAIN_VALIDATE_ERROR`;

export const DOMAIN_CREATE = `${ns}/DOMAIN_CREATE`;
export const DOMAIN_CREATE_ERROR = `${ns}/DOMAIN_CREATE_ERROR`;
export const DOMAIN_CREATE_SUCCESS = `${ns}/DOMAIN_CREATE_SUCCESS`;

export const DOMAIN_CREATE_TX = `${ns}/DOMAIN_CREATE_TX`;
export const DOMAIN_CREATE_TX_ERROR = `${ns}/DOMAIN_CREATE_TX_ERROR`;
export const DOMAIN_CREATE_TX_SUCCESS = `${ns}/DOMAIN_CREATE_TX_SUCCESS`;

export const DOMAIN_FETCH = `${ns}/DOMAIN_FETCH`;
export const DOMAIN_FETCH_ERROR = `${ns}/DOMAIN_FETCH_ERROR`;
export const DOMAIN_FETCH_SUCCESS = `${ns}/DOMAIN_FETCH_SUCCESS`;
