/* @flow */
/* eslint-disable max-len */

import ns from '../namespace';

export const TASK_CREATE = `${ns}/TASK_CREATE`;
export const TASK_CREATE_ERROR = `${ns}/TASK_CREATE_ERROR`;
export const TASK_CREATE_SUCCESS = `${ns}/TASK_CREATE_SUCCESS`;
export const TASK_CREATE_TRANSACTION_SENT = `${ns}/TASK_CREATE_TRANSACTION_SENT`;

export const TASK_EDIT = `${ns}/TASK_EDIT`;
export const TASK_EDIT_ERROR = `${ns}/TASK_EDIT_ERROR`;
export const TASK_EDIT_SUCCESS = `${ns}/TASK_EDIT_SUCCESS`;

export const TASK_UPDATE = `${ns}/TASK_UPDATE`;
export const TASK_UPDATE_ERROR = `${ns}/TASK_UPDATE_ERROR`;
export const TASK_UPDATE_SUCCESS = `${ns}/TASK_UPDATE_SUCCESS`;
export const TASK_UPDATE_TRANSACTION_SENT = `${ns}/TASK_UPDATE_TRANSACTION_SENT`;

export const TASK_WORKER_END = `${ns}/TASK_WORKER_END`;
export const TASK_WORKER_END_ERROR = `${ns}/TASK_WORKER_END_ERROR`;
export const TASK_WORKER_END_SUCCESS = `${ns}/TASK_WORKER_END_SUCCESS`;

export const TASK_MANAGER_END = `${ns}/TASK_MANAGER_END`;
export const TASK_MANAGER_END_ERROR = `${ns}/TASK_MANAGER_END_ERROR`;
export const TASK_MANAGER_END_SUCCESS = `${ns}/TASK_MANAGER_END_SUCCESS`;

export const TASK_MANAGER_COMPLETE = `${ns}/TASK_MANAGER_COMPLETE`;
export const TASK_MANAGER_COMPLETE_ERROR = `${ns}/TASK_MANAGER_COMPLETE_ERROR`;
export const TASK_MANAGER_COMPLETE_SUCCESS = `${ns}/TASK_MANAGER_COMPLETE_SUCCESS`;

export const TASK_MANAGER_RATE_WORKER = `${ns}/TASK_MANAGER_RATE_WORKER`;
export const TASK_MANAGER_RATE_WORKER_ERROR = `${ns}/TASK_MANAGER_RATE_WORKER_ERROR`;
export const TASK_MANAGER_RATE_WORKER_SUCCESS = `${ns}/TASK_MANAGER_RATE_WORKER_SUCCESS`;

export const TASK_WORKER_RATE_MANAGER = `${ns}/TASK_WORKER_RATE_MANAGER`;
export const TASK_WORKER_RATE_MANAGER_ERROR = `${ns}/TASK_WORKER_RATE_MANAGER_ERROR`;
export const TASK_WORKER_RATE_MANAGER_SUCCESS = `${ns}/TASK_WORKER_RATE_MANAGER_SUCCESS`;

export const TASK_MANAGER_REVEAL_WORKER_RATING = `${ns}/TASK_MANAGER_REVEAL_WORKER_RATING`;
export const TASK_MANAGER_REVEAL_WORKER_RATING_ERROR = `${ns}/TASK_MANAGER_REVEAL_WORKER_RATING_ERROR`;
export const TASK_MANAGER_REVEAL_WORKER_RATING_SUCCESS = `${ns}/TASK_MANAGER_REVEAL_WORKER_RATING_SUCCESS`;

export const TASK_WORKER_REVEAL_MANAGER_RATING = `${ns}/TASK_WORKER_REVEAL_MANAGER_RATING`;
export const TASK_WORKER_REVEAL_MANAGER_RATING_ERROR = `${ns}/TASK_WORKER_REVEAL_MANAGER_RATING_ERROR`;
export const TASK_WORKER_REVEAL_MANAGER_RATING_SUCCESS = `${ns}/TASK_WORKER_REVEAL_MANAGER_RATING_SUCCESS`;
