/* @flow */
/* eslint-disable max-len */

import ns from '../namespace';

export const TASK_WORKER_END = `${ns}/TASK_WORKER_END`;
export const TASK_WORKER_END_ERROR = `${ns}/TASK_WORKER_END_ERROR`;
export const TASK_WORKER_END_SUCCESS = `${ns}/TASK_WORKER_END_SUCCESS`;

export const TASK_MANAGER_END = `${ns}/TASK_MANAGER_END`;
export const TASK_MANAGER_END_ERROR = `${ns}/TASK_MANAGER_END_ERROR`;
export const TASK_MANAGER_END_SUCCESS = `${ns}/TASK_MANAGER_END_SUCCESS`;

export const TASK_MANAGER_COMPLETE = `${ns}/TASK_MANAGER_COMPLETE`;
export const TASK_MANAGER_COMPLETE_ERROR = `${ns}/TASK_MANAGER_COMPLETE_ERROR`;
export const TASK_MANAGER_COMPLETE_SUCCESS = `${ns}/TASK_MANAGER_COMPLETE_SUCCESS`;

export const TASK_MANAGER_RATE_WORKER = `${ns}/TASK_MANAGER_RATE_WORKER`;
export const TASK_MANAGER_RATE_WORKER_ERROR = `${ns}/TASK_MANAGER_RATE_WORKER_ERROR`;
export const TASK_MANAGER_RATE_WORKER_SUCCESS = `${ns}/TASK_MANAGER_RATE_WORKER_SUCCESS`;

export const TASK_WORKER_RATE_MANAGER = `${ns}/TASK_WORKER_RATE_MANAGER`;
export const TASK_WORKER_RATE_MANAGER_ERROR = `${ns}/TASK_WORKER_RATE_MANAGER_ERROR`;
export const TASK_WORKER_RATE_MANAGER_SUCCESS = `${ns}/TASK_WORKER_RATE_MANAGER_SUCCESS`;
