/* @flow */

import { DASHBOARD_NAMESPACE as ns } from '../constants';

export const TOKEN_CREATE = `${ns}/TOKEN_CREATE`;
export const TOKEN_CREATE_ERROR = `${ns}/TOKEN_CREATE_ERROR`;
export const TOKEN_CREATE_SUCCESS = `${ns}/TOKEN_CREATE_SUCCESS`;

export const TOKEN_INFO_FETCH = `${ns}/TOKEN_INFO_FETCH`;
export const TOKEN_INFO_FETCH_ERROR = `${ns}/TOKEN_INFO_FETCH_ERROR`;
export const TOKEN_INFO_FETCH_SUCCESS = `${ns}/TOKEN_INFO_FETCH_SUCCESS`;

export const TOKEN_ICON_FETCH = `${ns}/TOKEN_ICON_FETCH`;
export const TOKEN_ICON_FETCH_ERROR = `${ns}/TOKEN_ICON_FETCH_ERROR`;
export const TOKEN_ICON_FETCH_SUCCESS = `${ns}/TOKEN_ICON_FETCH_SUCCESS`;

export const TOKEN_ICON_UPLOAD = `${ns}/TOKEN_ICON_UPLOAD`;
export const TOKEN_ICON_UPLOAD_ERROR = `${ns}/TOKEN_ICON_UPLOAD_ERROR`;
export const TOKEN_ICON_UPLOAD_SUCCESS = `${ns}/TOKEN_ICON_UPLOAD_SUCCESS`;
