export const wideButton: string;
export const modalHeading: string;
export const headingContainer: string;
export const noPermissionMessage: string;
export const note: string;
export const learnMoreLink: string;
export const unlocked: string;
export const wrapper: string;
export const motionVoteDomain: string;
