export const sidebarHeight: string;
export const marginTop: string;
export const marginLeft: string;
export const marginRight: string;
export const marginBottom: string;
export const wrapper: string;
export const formWrapper: string;
export const title: string;
export const contentWrapper: string;
