export const paddingRightLeft: string;
export const circlePlusIcon: string;
export const container: string;
export const header: string;
export const fundingSourceLabel: string;
export const deleteIcon: string;
export const singleFundingSource: string;
export const addFundingSourceLabel: string;
export const marginBottomLarge: string;
