export const title: string;
export const description: string;
export const main: string;
export const stateDisabled: string;
export const iconCaret: string;
export const iconTitle: string;
export const coming: string;
export const iconWarning: string;
export const tooltip: string;
