export const sidebarWidth: string;
export const navBarHeight: string;
export const main: string;
export const sidebar: string;
export const wrapper: string;
export const spinnerContainer: string;
export const mainContainer: string;
export const mainContent: string;
export const smallerPadding: string;
