// flow-typed signature: d635e8236ab4da80c4cd84a9bf297a8a
// flow-typed version: <<STUB>>/es6-promisify_v^6.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promisify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promisify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-promisify/dist/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-promisify/dist/promisify.js' {
  declare module.exports: $Exports<'es6-promisify/dist/promisify'>;
}
