// flow-typed signature: 06ba94220c1dd3cf6bc3c854a1e732e6
// flow-typed version: <<STUB>>/ethers_v2.2.6/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethers/dist/ethers-contracts' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-contracts.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-providers' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-providers.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-utils' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-utils.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-wallet' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers-wallet.min' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers' {
  declare module.exports: any;
}

declare module 'ethers/dist/ethers.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethers/dist/ethers-contracts.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-contracts'>;
}
declare module 'ethers/dist/ethers-contracts.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-contracts.min'>;
}
declare module 'ethers/dist/ethers-providers.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-providers'>;
}
declare module 'ethers/dist/ethers-providers.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-providers.min'>;
}
declare module 'ethers/dist/ethers-utils.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-utils'>;
}
declare module 'ethers/dist/ethers-utils.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-utils.min'>;
}
declare module 'ethers/dist/ethers-wallet.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-wallet'>;
}
declare module 'ethers/dist/ethers-wallet.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers-wallet.min'>;
}
declare module 'ethers/dist/ethers.js' {
  declare module.exports: $Exports<'ethers/dist/ethers'>;
}
declare module 'ethers/dist/ethers.min.js' {
  declare module.exports: $Exports<'ethers/dist/ethers.min'>;
}
declare module 'ethers/index' {
  declare module.exports: $Exports<'ethers'>;
}
declare module 'ethers/index.js' {
  declare module.exports: $Exports<'ethers'>;
}
