// flow-typed signature: 3d9671fb6fbb145ad51d77b2fca02e92
// flow-typed version: <<STUB>>/revalidate_v^1.2.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'revalidate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'revalidate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'revalidate/assertions' {
  declare module.exports: any;
}

declare module 'revalidate/immutable' {
  declare module.exports: any;
}

declare module 'revalidate/lib/assertions' {
  declare module.exports: any;
}

declare module 'revalidate/lib/combineValidators' {
  declare module.exports: any;
}

declare module 'revalidate/lib/composeValidators' {
  declare module.exports: any;
}

declare module 'revalidate/lib/createValidator' {
  declare module.exports: any;
}

declare module 'revalidate/lib/createValidatorFactory' {
  declare module.exports: any;
}

declare module 'revalidate/lib/immutable' {
  declare module.exports: any;
}

declare module 'revalidate/lib/index' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/createValidatorWithMultipleErrors' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/createValidatorWithSingleError' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/ensureNestedValidators' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/fillObjectFromPath' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/index' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/internalCombineNestedValidators' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/internalCombineValidators' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/isValueValidator' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/markAsValueValidator' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/parseFieldName' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/sym' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/symbols' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/validators/internalMatchesPattern' {
  declare module.exports: any;
}

declare module 'revalidate/lib/internal/valueMissing' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/hasLengthBetween' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/hasLengthGreaterThan' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/hasLengthLessThan' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isAlphabetic' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isAlphaNumeric' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isNumeric' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isOneOf' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isRequired' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/isRequiredIf' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/matchesField' {
  declare module.exports: any;
}

declare module 'revalidate/lib/validators/matchesPattern' {
  declare module.exports: any;
}

declare module 'revalidate/src/assertions' {
  declare module.exports: any;
}

declare module 'revalidate/src/combineValidators' {
  declare module.exports: any;
}

declare module 'revalidate/src/composeValidators' {
  declare module.exports: any;
}

declare module 'revalidate/src/createValidator' {
  declare module.exports: any;
}

declare module 'revalidate/src/createValidatorFactory' {
  declare module.exports: any;
}

declare module 'revalidate/src/immutable' {
  declare module.exports: any;
}

declare module 'revalidate/src/index' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/createValidatorWithMultipleErrors' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/createValidatorWithSingleError' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/ensureNestedValidators' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/fillObjectFromPath' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/index' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/internalCombineNestedValidators' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/internalCombineValidators' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/isValueValidator' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/markAsValueValidator' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/parseFieldName' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/sym' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/symbols' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/validators/internalMatchesPattern' {
  declare module.exports: any;
}

declare module 'revalidate/src/internal/valueMissing' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/hasLengthBetween' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/hasLengthGreaterThan' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/hasLengthLessThan' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isAlphabetic' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isAlphaNumeric' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isNumeric' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isOneOf' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isRequired' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/isRequiredIf' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/matchesField' {
  declare module.exports: any;
}

declare module 'revalidate/src/validators/matchesPattern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'revalidate/assertions.js' {
  declare module.exports: $Exports<'revalidate/assertions'>;
}
declare module 'revalidate/immutable.js' {
  declare module.exports: $Exports<'revalidate/immutable'>;
}
declare module 'revalidate/lib/assertions.js' {
  declare module.exports: $Exports<'revalidate/lib/assertions'>;
}
declare module 'revalidate/lib/combineValidators.js' {
  declare module.exports: $Exports<'revalidate/lib/combineValidators'>;
}
declare module 'revalidate/lib/composeValidators.js' {
  declare module.exports: $Exports<'revalidate/lib/composeValidators'>;
}
declare module 'revalidate/lib/createValidator.js' {
  declare module.exports: $Exports<'revalidate/lib/createValidator'>;
}
declare module 'revalidate/lib/createValidatorFactory.js' {
  declare module.exports: $Exports<'revalidate/lib/createValidatorFactory'>;
}
declare module 'revalidate/lib/immutable.js' {
  declare module.exports: $Exports<'revalidate/lib/immutable'>;
}
declare module 'revalidate/lib/index.js' {
  declare module.exports: $Exports<'revalidate/lib/index'>;
}
declare module 'revalidate/lib/internal/createValidatorWithMultipleErrors.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/createValidatorWithMultipleErrors'>;
}
declare module 'revalidate/lib/internal/createValidatorWithSingleError.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/createValidatorWithSingleError'>;
}
declare module 'revalidate/lib/internal/ensureNestedValidators.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/ensureNestedValidators'>;
}
declare module 'revalidate/lib/internal/fillObjectFromPath.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/fillObjectFromPath'>;
}
declare module 'revalidate/lib/internal/index.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/index'>;
}
declare module 'revalidate/lib/internal/internalCombineNestedValidators.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/internalCombineNestedValidators'>;
}
declare module 'revalidate/lib/internal/internalCombineValidators.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/internalCombineValidators'>;
}
declare module 'revalidate/lib/internal/isValueValidator.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/isValueValidator'>;
}
declare module 'revalidate/lib/internal/markAsValueValidator.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/markAsValueValidator'>;
}
declare module 'revalidate/lib/internal/parseFieldName.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/parseFieldName'>;
}
declare module 'revalidate/lib/internal/sym.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/sym'>;
}
declare module 'revalidate/lib/internal/symbols.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/symbols'>;
}
declare module 'revalidate/lib/internal/validators/internalMatchesPattern.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/validators/internalMatchesPattern'>;
}
declare module 'revalidate/lib/internal/valueMissing.js' {
  declare module.exports: $Exports<'revalidate/lib/internal/valueMissing'>;
}
declare module 'revalidate/lib/validators/hasLengthBetween.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/hasLengthBetween'>;
}
declare module 'revalidate/lib/validators/hasLengthGreaterThan.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/hasLengthGreaterThan'>;
}
declare module 'revalidate/lib/validators/hasLengthLessThan.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/hasLengthLessThan'>;
}
declare module 'revalidate/lib/validators/isAlphabetic.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isAlphabetic'>;
}
declare module 'revalidate/lib/validators/isAlphaNumeric.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isAlphaNumeric'>;
}
declare module 'revalidate/lib/validators/isNumeric.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isNumeric'>;
}
declare module 'revalidate/lib/validators/isOneOf.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isOneOf'>;
}
declare module 'revalidate/lib/validators/isRequired.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isRequired'>;
}
declare module 'revalidate/lib/validators/isRequiredIf.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/isRequiredIf'>;
}
declare module 'revalidate/lib/validators/matchesField.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/matchesField'>;
}
declare module 'revalidate/lib/validators/matchesPattern.js' {
  declare module.exports: $Exports<'revalidate/lib/validators/matchesPattern'>;
}
declare module 'revalidate/src/assertions.js' {
  declare module.exports: $Exports<'revalidate/src/assertions'>;
}
declare module 'revalidate/src/combineValidators.js' {
  declare module.exports: $Exports<'revalidate/src/combineValidators'>;
}
declare module 'revalidate/src/composeValidators.js' {
  declare module.exports: $Exports<'revalidate/src/composeValidators'>;
}
declare module 'revalidate/src/createValidator.js' {
  declare module.exports: $Exports<'revalidate/src/createValidator'>;
}
declare module 'revalidate/src/createValidatorFactory.js' {
  declare module.exports: $Exports<'revalidate/src/createValidatorFactory'>;
}
declare module 'revalidate/src/immutable.js' {
  declare module.exports: $Exports<'revalidate/src/immutable'>;
}
declare module 'revalidate/src/index.js' {
  declare module.exports: $Exports<'revalidate/src/index'>;
}
declare module 'revalidate/src/internal/createValidatorWithMultipleErrors.js' {
  declare module.exports: $Exports<'revalidate/src/internal/createValidatorWithMultipleErrors'>;
}
declare module 'revalidate/src/internal/createValidatorWithSingleError.js' {
  declare module.exports: $Exports<'revalidate/src/internal/createValidatorWithSingleError'>;
}
declare module 'revalidate/src/internal/ensureNestedValidators.js' {
  declare module.exports: $Exports<'revalidate/src/internal/ensureNestedValidators'>;
}
declare module 'revalidate/src/internal/fillObjectFromPath.js' {
  declare module.exports: $Exports<'revalidate/src/internal/fillObjectFromPath'>;
}
declare module 'revalidate/src/internal/index.js' {
  declare module.exports: $Exports<'revalidate/src/internal/index'>;
}
declare module 'revalidate/src/internal/internalCombineNestedValidators.js' {
  declare module.exports: $Exports<'revalidate/src/internal/internalCombineNestedValidators'>;
}
declare module 'revalidate/src/internal/internalCombineValidators.js' {
  declare module.exports: $Exports<'revalidate/src/internal/internalCombineValidators'>;
}
declare module 'revalidate/src/internal/isValueValidator.js' {
  declare module.exports: $Exports<'revalidate/src/internal/isValueValidator'>;
}
declare module 'revalidate/src/internal/markAsValueValidator.js' {
  declare module.exports: $Exports<'revalidate/src/internal/markAsValueValidator'>;
}
declare module 'revalidate/src/internal/parseFieldName.js' {
  declare module.exports: $Exports<'revalidate/src/internal/parseFieldName'>;
}
declare module 'revalidate/src/internal/sym.js' {
  declare module.exports: $Exports<'revalidate/src/internal/sym'>;
}
declare module 'revalidate/src/internal/symbols.js' {
  declare module.exports: $Exports<'revalidate/src/internal/symbols'>;
}
declare module 'revalidate/src/internal/validators/internalMatchesPattern.js' {
  declare module.exports: $Exports<'revalidate/src/internal/validators/internalMatchesPattern'>;
}
declare module 'revalidate/src/internal/valueMissing.js' {
  declare module.exports: $Exports<'revalidate/src/internal/valueMissing'>;
}
declare module 'revalidate/src/validators/hasLengthBetween.js' {
  declare module.exports: $Exports<'revalidate/src/validators/hasLengthBetween'>;
}
declare module 'revalidate/src/validators/hasLengthGreaterThan.js' {
  declare module.exports: $Exports<'revalidate/src/validators/hasLengthGreaterThan'>;
}
declare module 'revalidate/src/validators/hasLengthLessThan.js' {
  declare module.exports: $Exports<'revalidate/src/validators/hasLengthLessThan'>;
}
declare module 'revalidate/src/validators/isAlphabetic.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isAlphabetic'>;
}
declare module 'revalidate/src/validators/isAlphaNumeric.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isAlphaNumeric'>;
}
declare module 'revalidate/src/validators/isNumeric.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isNumeric'>;
}
declare module 'revalidate/src/validators/isOneOf.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isOneOf'>;
}
declare module 'revalidate/src/validators/isRequired.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isRequired'>;
}
declare module 'revalidate/src/validators/isRequiredIf.js' {
  declare module.exports: $Exports<'revalidate/src/validators/isRequiredIf'>;
}
declare module 'revalidate/src/validators/matchesField.js' {
  declare module.exports: $Exports<'revalidate/src/validators/matchesField'>;
}
declare module 'revalidate/src/validators/matchesPattern.js' {
  declare module.exports: $Exports<'revalidate/src/validators/matchesPattern'>;
}
