/* @flow */

import ns from '../namespace';

export const METHOD_TRANSACTION_SENT = `${ns}/METHOD_TRANSACTION_SENT`;
export const TRANSACTION_CREATED = `${ns}/TRANSACTION_CREATED`;
export const TRANSACTION_READY = `${ns}/TRANSACTION_READY`;
export const TRANSACTION_ERROR = `${ns}/TRANSACTION_ERROR`;
export const TRANSACTION_EVENT_DATA_RECEIVED = `${ns}/TRANSACTION_EVENT_DATA_RECEIVED`;
export const TRANSACTION_GAS_SUGGESTED = `${ns}/TRANSACTION_GAS_SUGGESTED`;
export const TRANSACTION_GAS_MANUAL = `${ns}/TRANSACTION_GAS_MANUAL`;
export const TRANSACTION_RECEIPT_RECEIVED = `${ns}/TRANSACTION_RECEIPT_RECEIVED`;
export const TRANSACTION_SENT = `${ns}/TRANSACTION_SENT`;
