/* @flow */

import ns from '../namespace';

export const METHOD_TRANSACTION_SENT = `${ns}/METHOD_TRANSACTION_SENT`;
export const MULTISIG_TRANSACTION_CREATED = `${ns}/MULTISIG_TRANSACTION_CREATED`;
export const MULTISIG_TRANSACTION_REFRESHED = `${ns}/MULTISIG_TRANSACTION_REFRESHED`;
export const MULTISIG_TRANSACTION_REJECT = `${ns}/MULTISIG_TRANSACTION_REJECT`;
export const MULTISIG_TRANSACTION_SIGN = `${ns}/MULTISIG_TRANSACTION_SIGN`;
export const MULTISIG_TRANSACTION_SIGNED = `${ns}/MULTISIG_TRANSACTION_SIGNED`;
export const TRANSACTION_CREATED = `${ns}/TRANSACTION_CREATED`;
export const TRANSACTION_ERROR = `${ns}/TRANSACTION_ERROR`;
export const TRANSACTION_EVENT_DATA_RECEIVED = `${ns}/TRANSACTION_EVENT_DATA_RECEIVED`;
export const TRANSACTION_ESTIMATE_GAS = `${ns}/TRANSACTION_ESTIMATE_GAS`;
export const TRANSACTION_GAS_UPDATE = `${ns}/TRANSACTION_GAS_UPDATE`;
export const TRANSACTION_RECEIPT_RECEIVED = `${ns}/TRANSACTION_RECEIPT_RECEIVED`;
export const TRANSACTION_SENT = `${ns}/TRANSACTION_SENT`;
export const GAS_PRICES_UPDATE = `${ns}/GAS_PRICES_UPDATE`;
