/* @flow */
/* eslint-disable max-len */

import { CORE_NAMESPACE as ns } from '../namespace';

export const TRANSACTION_EVENT_DATA_ERROR = `${ns}/TRANSACTION_EVENT_DATA_ERROR`;
export const TRANSACTION_EVENT_DATA_RECEIVED = `${ns}/TRANSACTION_EVENT_DATA_RECEIVED`;
export const TRANSACTION_RECEIPT_ERROR = `${ns}/TRANSACTION_RECEIPT_ERROR`;
export const TRANSACTION_RECEIPT_RECEIVED = `${ns}/TRANSACTION_RECEIPT_RECEIVED`;
export const TRANSACTION_SEND_ERROR = `${ns}/TRANSACTION_SEND_ERROR`;
export const TRANSACTION_SENT = `${ns}/TRANSACTION_SENT`;
export const TRANSACTION_STARTED = `${ns}/TRANSACTION_STARTED`;
