export const defaultDotBackground: string;
export const wrapper: string;
export const title: string;
export const avatars: string;
export const status: string;
export const statusApproved: string;
export const progressBarLabel: string;
export const controls: string;
export const totalRequired: string;
