export const main: string;
export const coloniesList: string;
export const contentWrapper: string;
export const content: string;
export const title: string;
export const item: string;
export const itemLink: string;
export const itemIcon: string;
export const itemTitle: string;
