export const query700: string;
export const layoutMain: string;
export const header: string;
export const logo: string;
export const hero: string;
export const herowrapper: string;
export const title: string;
export const description: string;
export const nakedMole: string;
