export const paddingRightLeft: string;
export const paymentContainer: string;
export const split: string;
export const splitToggle: string;
export const recipientWrapper: string;
export const recipientsWrapper: string;
export const deleteIcon: string;
export const addRecipientLabel: string;
export const circlePlusIcon: string;
