export const wrapper: string;
export const step: string;
export const title: string;
export const titleText: string;
export const fieldWrapper: string;
export const required: string;
export const groupTitle: string;
export const subtitle: string;
export const commercialWrapper: string;
