export const main: string;
export const notEditingValueWrapper: string;
export const notEditingValueContainer: string;
export const notEditingValue: string;
export const inputContainer: string;
export const maxLengthText: string;
export const stateHasValue: string;
export const stateHasReachedMaxLength: string;
export const stateReadOnly: string;
