import { getLogs, ColonyClientV5 } from '@colony/colony-js';

import { Address } from '~types/index';

export const getAnnotation = async (
  agent: Address,
  transactionHash: string,
  /*
   * @NOTE Only version 5 of colony has access to the Annotation
   * (both filter and the actual method call)
   */
  colonyClient: ColonyClientV5,
) => {
  /*
   * @TODO For some reason types were not autogenerated in colonyJS for this filter
   * I need, at some point, to investigate what's up
   */
  const filter = colonyClient.filters.Annotation(agent, transactionHash, null);
  const allColonyAnnotationLogs = await getLogs(colonyClient, filter);
  const allColonyParseAnnotations = allColonyAnnotationLogs.map(
    (annotationLog) => colonyClient.interface.parseLog(annotationLog),
  );
  return allColonyParseAnnotations.pop();
};
