export const headingContainer: string;
export const headingInner: string;
export const iconComplete: string;
export const categories: string;
export const category: string;
export const rewardsContainer: string;
export const payoutsContainer: string;
export const pendingText: string;
export const dot: string;
