export const paddingVertical: string;
export const paddingHorizontal: string;
export const main: string;
export const actionMenuContainer: string;
export const titleContainer: string;
export const authorText: string;
export const upvoteContainer: string;
export const upvoteCount: string;
export const upvoteButtonContainer: string;
