export const row: string;
export const amount: string;
export const editContainer: string;
export const selectToken: string;
export const setAmount: string;
export const reputation: string;
export const conversion: string;
export const fundingDetails: string;
export const networkFeeRow: string;
