export const marginSize: string;
export const wideButton: string;
export const tokenChoiceContainer: string;
export const description: string;
export const textarea: string;
export const noPermissionMessage: string;
export const modalHeading: string;
export const headingContainer: string;
export const motionVoteDomain: string;
