export const toggleHeight: string;
export const toggleWidth: string;
export const container: string;
export const delegate: string;
export const toggle: string;
export const toggleDisabled: string;
export const toggleSwitch: string;
export const checked: string;
export const icon: string;
