export const query700: string;
export const main: string;
export const walletDetails: string;
export const walletHeading: string;
export const walletAddress: string;
export const actionsContainer: string;
export const goToWalletIcon: string;
export const closeButton: string;
export const connectedNetwork: string;
