export const item: string;
export const value: string;
export const label: string;
export const penaltyValue: string;
export const descriptionValue: string;
export const transactionHashLink: string;
export const domainDescriptionItem: string;
export const domainDescription: string;
export const roleSettingItem: string;
