export const main: string;
export const statusSchemaInfo: string;
export const directionHorizontal: string;
export const stateHidden: string;
export const stateError: string;
export const themeFat: string;
export const themeUnderlined: string;
export const themeMinimal: string;
export const textSpaceWrap: string;
