export const teamWrapper: string;
export const changeContainer: string;
export const row: string;
export const arrowIcon: string;
export const left: string;
export const right: string;
export const buttonWrappper: string;
export const discard: string;
export const subheader: string;
