export const main: string;
export const section: string;
export const usernameSection: string;
export const displayName: string;
export const username: string;
export const address: string;
export const reputationSection: string;
export const stateHasReputation: string;
export const stateReputationLoaded: string;
