export const spaceBetween: string;
export const content: string;
export const button: string;
export const amount: string;
export const amountWrapper: string;
export const date: string;
export const details: string;
export const sender: string;
export const arrowIcon: string;
