export const selectHeight: string;
export const wrapper: string;
export const step: string;
export const title: string;
export const addressWrapper: string;
export const fieldWrapper: string;
export const uploadWrapper: string;
export const selectWrapper: string;
export const placeholder: string;
