export const tableRadii: string;
export const baseStyles: string;
export const stateScrollable: string;
export const separatorsBorders: string;
export const separatorsRows: string;
export const main: string;
export const themeDark: string;
export const themeRounder: string;
export const themeLined: string;
