export const buttonHeight: string;
export const buttonWidth: string;
export const mainContainer: string;
export const status: string;
export const notSaved: string;
export const stagesText: string;
export const statusContainer: string;
export const icon: string;
export const buttonsContainer: string;
