export const domainSelectItem: string;
export const domainSelectItemChildDomainIcon: string;
export const domainSelectItemTitle: string;
export const domainSelectItemColor: string;
export const domainSelectItemMainContent: string;
export const domainSelectItemRootText: string;
export const domainSelectItemDescription: string;
export const editButtonCol: string;
export const editButton: string;
