export const main: string;
export const themeWhite: string;
export const themeDanger: string;
export const header: string;
export const value: string;
export const valueWarning: string;
export const footerText: string;
export const tooltipIcon: string;
export const tooltip: string;
