/* @flow */

import ns from '../namespace';

export const COLONY_FETCH_TRANSACTIONS = `${ns}/COLONY_FETCH_TRANSACTIONS`;
export const COLONY_FETCH_TRANSACTIONS_SUCCESS = `${ns}/COLONY_FETCH_TRANSACTIONS_SUCCESS`;
export const COLONY_FETCH_TRANSACTIONS_ERROR = `${ns}/COLONY_FETCH_TRANSACTIONS_ERROR`;

export const COLONY_FETCH_UNCLAIMED_TRANSACTIONS = `${ns}/COLONY_FETCH_UNCLAIMED_TRANSACTIONS`;
export const COLONY_FETCH_UNCLAIMED_TRANSACTIONS_SUCCESS = `${ns}/COLONY_FETCH_UNCLAIMED_TRANSACTIONS_SUCCESS`;
export const COLONY_FETCH_UNCLAIMED_TRANSACTIONS_ERROR = `${ns}/COLONY_FETCH_UNCLAIMED_TRANSACTIONS_ERROR`;

export const COLONY_CLAIM_TOKEN = `${ns}/COLONY_CLAIM_TOKEN`;
export const COLONY_CLAIM_TOKEN_SUCCESS = `${ns}/COLONY_CLAIM_TOKEN_SUCCESS`;
export const COLONY_CLAIM_TOKEN_ERROR = `${ns}/COLONY_CLAIM_TOKEN_ERROR`;
