export const main: string;
export const themeFat: string;
export const themeUnderlined: string;
export const themeMinimal: string;
export const themeDotted: string;
export const alignRight: string;
export const sizeSmall: string;
export const colorSchemaDark: string;
export const colorSchemaTransparent: string;
