export const baseSelect: string;
export const main: string;
export const selectInner: string;
export const inputWrapper: string;
export const select: string;
export const selectExpandContainer: string;
export const activeOption: string;
export const themeDefault: string;
export const themeAlt: string;
