export const container: string;
export const containerSuccess: string;
export const containerError: string;
export const msgText: string;
export const dot: string;
export const dotSuccess: string;
export const dotError: string;
export const fadeOut: string;
export const fadeIn: string;
