export const mainTextSize: string;
export const main: string;
export const avatar: string;
export const status: string;
export const stateRed: string;
export const stateBlue: string;
export const content: string;
export const title: string;
export const meta: string;
