export const passedColor: string;
export const failedColor: string;
export const wrapper: string;
export const titleWrapper: string;
export const statusWrapper: string;
export const line: string;
export const dot: string;
export const title: string;
export const link: string;
