import { ROOT_DOMAIN_ID } from '@colony/colony-js';
import React from 'react';
import { defineMessage, FormattedMessage } from 'react-intl';

import { getMainClasses } from '~utils/css';
import DialogSection from '~core/Dialog/DialogSection';
import ExternalLink from '~core/ExternalLink';
import { MD_REPUTATION_INFO } from '~externalUrls';

import styles from './NotEnoughReputation.css';

interface Appearance {
  marginTop?: 'negative';
}

interface Props {
  domainId?: number;
  appearance?: Appearance;
  includeForceCopy?: boolean;
}

const MSG = defineMessage({
  title: {
    id: 'NotEnoughReputation.title',
    defaultMessage: `There is no reputation in this {onRootDomain, select,
      true {colony}
      false {team}
    } yet.`,
  },
  description: {
    id: 'NotEnoughReputation.description',
    defaultMessage: `Reputation is generated by making payments
    to members with this colony’s native token.{includeForceCopy, select,
     true { If you have the necessary permissions to
     take this action you can toggle “Force”
     in the top right to bypass the governance process.}
     false {}
     } <a>Learn more</a>`,
  },
});

const displayName = 'NotEnoughReputation';

const NotEnoughReputation = ({
  domainId = ROOT_DOMAIN_ID,
  appearance,
  includeForceCopy = true,
}: Props) => (
  <div className={`${styles.container} ${getMainClasses(appearance, styles)}`}>
    <DialogSection appearance={{ theme: 'sidePadding' }}>
      <p className={styles.title}>
        <FormattedMessage
          {...MSG.title}
          values={{ onRootDomain: domainId === ROOT_DOMAIN_ID }}
        />
      </p>
      <p className={styles.text}>
        <FormattedMessage
          {...MSG.description}
          values={{
            a: (chunks) => (
              <ExternalLink href={MD_REPUTATION_INFO}>{chunks}</ExternalLink>
            ),
            includeForceCopy,
          }}
        />
      </p>
    </DialogSection>
  </div>
);

NotEnoughReputation.displayName = displayName;

export default NotEnoughReputation;
