export const main: string;
export const tableBody: string;
export const communityRole: string;
export const subscribeCallToAction: string;
export const subscribeButton: string;
export const subscribedIcon: string;
export const unsubscribedIcon: string;
export const titleContainer: string;
export const reputationPoints: string;
