export const main: string;
export const header: string;
export const labelContainer: string;
export const title: string;
export const nameForm: string;
export const tokenDetails: string;
export const input: string;
export const buttons: string;
export const linkToOtherStep: string;
