export const title: string;
export const requiredPermissionSection: string;
export const section: string;
export const sectionLabel: string;
export const labelIcon: string;
export const permissionList: string;
export const listItem: string;
export const tooltipText: string;
export const tooltipContent: string;
