export const main: string;
export const spinnerContainer: string;
export const colonySubscribed: string;
export const colonyJoin: string;
export const menuIconContainer: string;
export const menuActive: string;
export const colonyJoinBtn: string;
export const joinButton: string;
export const createUserRedirect: string;
