export const entryHoverColor: string;
export const main: string;
export const token: string;
export const tokenIconContainer: string;
export const tokenInfoContainer: string;
export const tokenInfoContainerActive: string;
export const tokenBalance: string;
export const tokenSymbol: string;
export const tokenIcon: string;
