export const wideButton: string;
export const main: string;
export const grid: string;
export const colonyInfo: string;
export const metaContainer: string;
export const content: string;
export const noTasks: string;
export const breadCrumbContainer: string;
export const sidebar: string;
