export const main: string;
export const colonyList: string;
export const mainContentGrid: string;
export const leftAside: string;
export const leftAsideNav: string;
export const mainContent: string;
export const contentActionsPanel: string;
export const rightAside: string;
export const events: string;
