export const query700: string;
export const main: string;
export const filter: string;
export const controls: string;
export const emptyState: string;
export const loadingSpinner: string;
export const bar: string;
export const title: string;
export const link: string;
