export const main: string;
export const header: string;
export const healthDetailsWrapper: string;
export const healthIconWrapper: string;
export const healthTitle: string;
export const healthDetails: string;
export const actionsContainer: string;
export const closeButton: string;
export const content: string;
