export const query700: string;
export const main: string;
export const mainContentGrid: string;
export const mainContent: string;
export const rightAside: string;
export const loadingWrapper: string;
export const controls: string;
export const teamReputationPointsContainer: string;
export const reputationPoints: string;
